// All data in this file has been generated by Perplexity

export const BEACONS = {
  "conv-hall": {
    id: "conv-hall",
    name: "Convocation Hall",
    historic: true,
    location: {
      latitude: 43.66075,
      longitude: -79.39541
    },
    description: "The iconic domed building where graduation ceremonies take place. Built in 1907, its circular design was inspired by ancient Greek theaters.",
  },
  "hart-house": {
    id: "hart-house",
    name: "Hart House",
    historic: true,
    location: {
      latitude: 43.6637,
      longitude: -79.3944
    },
    description: "A historic student activity center offering arts, culture and recreation since 1919. Features a historic gym, theatre, and art gallery.",
  },
  "bahen": {
    id: "bahen",
    name: "Bahen Centre",
    historic: false,
    location: {
      latitude: 43.65968,
      longitude: -79.39738
    },
    description: "Home to Computer Science and Engineering students. Known for its 24-hour access and countless study spaces.",
  },
  "myhal": {
    id: "myhal",
    name: "Myhal Centre",
    historic: false,
    location: {
      latitude: 43.66084,
      longitude: -79.39649
    },
    description: "The newest engineering building featuring state-of-the-art design studios and collaboration spaces.",
  },
  "robarts": {
    id: "robarts",
    name: "Robarts Library",
    historic: false,
    location: {
      latitude: 43.66454,
      longitude: -79.39938
    },
    description: "The massive concrete peacock of UofT. This brutalist library is the largest academic library in Canada.",
  },
  "galbraith": {
    id: "galbraith",
    name: "Galbraith Building",
    historic: false,
    location: {
      latitude: 43.66009,
      longitude: -79.39252
    },
    description: "The traditional home of Engineering at UofT. Look out for the famous cannon!",
  },
  "sid-smith": {
    id: "sid-smith",
    name: "Sidney Smith Hall",
    historic: false,
    location: {
      latitude: 43.66234,
      longitude: -79.39833
    },
    description: "Arts & Science hub with the famous Sid's Cafe. A central meeting point for students.",
  },
  "medical-sciences": {
    id: "medical-sciences",
    name: "Medical Sciences Building",
    historic: false,
    location: {
      latitude: 43.66089,
      longitude: -79.39333
    },
    description: "Center for medical research and education at UofT. Home to future doctors and researchers.",
  },
  "gerstein": {
    id: "gerstein",
    name: "Gerstein Library",
    historic: false,
    location: {
      latitude: 43.66222,
      longitude: -79.39333
    },
    description: "The science and health sciences library, housed in a beautiful historic building.",
  },
  "earth-sciences": {
    id: "earth-sciences",
    name: "Earth Sciences Centre",
    historic: false,
    location: {
      latitude: 43.66060,
      longitude: -79.39694
    },
    description: "Home to Earth Sciences and Chemistry departments, featuring indoor gardens.",
  },
  "mechanical": {
    id: "mechanical",
    name: "Mechanical Engineering Building",
    historic: false,
    location: {
      latitude: 43.65997,
      longitude: -79.39433
    },
    description: "Home to Mechanical and Industrial Engineering, featuring various labs and machine shops.",
  },
  "sandford-fleming": {
    id: "sandford-fleming",
    name: "Sandford Fleming Building",
    historic: true,
    location: {
      latitude: 43.66027,
      longitude: -79.39493
    },
    description: "Historic engineering building named after the inventor of Standard Time. Features the famous SF Cafeteria.",
  },
  "mclennan": {
    id: "mclennan",
    name: "McLennan Physical Labs",
    historic: false,
    location: {
      latitude: 43.66205,
      longitude: -79.39775
    },
    description: "Home to Physics and Astronomy departments. Connected to Burton Tower, featuring research labs and lecture halls.",
  },
};
